name: Pull Request
on: 
  pull_request:
    
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Deps
        run: npm install --save-dev @commitlint/{config-conventional,cli}
      - name: Run commitlint
        run: npx commitlint --from=${{ github.event.pull_request.base.sha }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1'
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1'
      - name: Install Deps
        run: go mod vendor
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test -mod=vendor --race -v ./...

